#环境配置
DebugMode: true #是否处于Debug模式
ServerPort: 9091
LogFile: /tmp/schedulx/logs/app.log
LogLevel: info
WriteDB:
  Name: schedulx
  Host: 127.0.0.1
  Port: 3306
  User: gf
  Password: db@galaxy-future.com
  Timeout: 50ms
  ReadTimeout: 800ms
  WriteTimeout: 800ms
  MaxIdleConns: 10
  MaxOpenConns: 30
ReadDB:
  Name: schedulx
  Host: 127.0.0.1
  Port: 3306
  User: gf
  Password: db@galaxy-future.com
  Timeout: 50ms
  ReadTimeout: 60ms
  WriteTimeout: 60ms
  MaxIdleConns: 10
  MaxOpenConns: 30
BridgXHost: http://127.0.0.1:9090
JwtToken:
  JwtTokenSignKey: "bridgx"   #设置token生成时加密的签名
  JwtTokenCreatedExpires: 28800   #创建时token默认有效秒数（token生成时间加上该时间秒数，算做有效期）,3600*8=28800 等于8小时
  JwtTokenRefreshExpires: 36000  #对于过期的token，支持从相关接口刷新获取新的token，它有效期为10个小时，3600*10=36000 等于10小时
  BindContextKeyName: "userToken"  #用户在 header 头部提交的token绑定到上下文时的键名，方便直接从上下文(gin.context)直接获取每个用户的id等信息
AlibabaCloudAccount:
  Region: ""  #配置开源需要删除
  AccessKey: "" #配置开源需要删除
  Secret: "" #配置开源需要删除